apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: spark-operator
  namespace: spark-operator
spec:
  interval: 30m
  url: https://googlecloudplatform.github.io/spark-on-k8s-operator