apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: yugabytedb
  namespace: yugabytedb
spec:
  interval: 5m
  targetNamespace: yugabytedb
  chart:
    spec:
      chart: yugabyte
      version: "v1.5.2"
      sourceRef:
        kind: HelmRepository
        name: yugabytedb
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
  # https://github.com/yugabyte/charts/blob/master/stable/yugabyte/values.yaml