apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: yugabytedb
  namespace: yugabytedb
spec:
  interval: 5m
  targetNamespace: yugabytedb
  chart:
    spec:
      chart: yugabyte
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: yugabytedb
        namespace: flux-system
      interval: 1m
  install:
    timeout: 10m
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
  # https://artifacthub.io/packages/helm/yugabyte/yugabyte
  # https://github.com/yugabyte/charts/blob/master/stable/yugabyte/values.yaml