apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
spec:
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3