apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  chart:
    spec:
      chart: mysql
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  releaseName: mysql
  values:
  # https://github.com/bitnami/charts/blob/main/bitnami/mysql/values.yaml