apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 11.3.4
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  interval: 5m
  releaseName: teleport
  targetNamespace: teleport
  test:
    enable: false # Enable helm test
  install:
    crds: CreateReplace
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 10m
  values:
  # https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml
    persistence:
      enabled: false