apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
  # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml