apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kaniko
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./orchestration/kaniko
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system