apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
  namespace: superset
spec:
  releaseName: superset
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system
  interval: 1h0m0s