apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-internal
  namespace: ingress
spec:
  interval: 3m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.2.5'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 3m
  values:
    controller:
      config:
        http2-max-field-size: "32k"
        large-client-header-buffers: "4 64k"
      replicaCount: 2
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
    defaultBackend:
      resources:
        requests:
          memory: 32Mi