apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/data-engineering/kafka
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system