apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 12.2.0
  install:
    timeout: 10m
    remediation:
      retries: 3
  interval: 5m
  values:
  # https://artifacthub.io/packages/helm/bitnami/postgresql
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
    global:
      postgresql:
        auth:
          # username: postgres
          postgresPassword: "postgres"
          # psql -U postgres
    persistence:
      size: 1Gi