apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyter
  namespace: jupyter
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: jupyter
        namespace: flux-system
  install:
    remediation:
      retries: 5
  values:
  # https://artifacthub.io/packages/helm/jupyterhub/jupyterhub
  # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml
    hub:
      config:
        Authenticator:
          auto_login: true
    proxy:
      service:
        type: ClusterIP
    