apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  interval: 1h0m0s
  timeout: 10m0s
  targetNamespace: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
  # https://artifacthub.io/packages/helm/policy-reporter/policy-reporter
  # https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml
    ui:
      enabled: true
    global:
      plugins:
        kyverno: true

