apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      version: 'v1.0.1'
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  interval: 10m
  releaseName: reloader
  install:
    crds: Create
  upgrade:
    crds: CreateReplace