apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./compliance/kyverno
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system