apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pinot
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/apache/pinot/tree/master/kubernetes/helm/pinot