apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pinot
  namespace: pinot
spec:
  releaseName: pinot
  chart:
    spec:
      chart: pinot
      sourceRef:
        kind: HelmRepository
        name: pinot
        namespace: flux-system
  interval: 1h0m0s
  values:
  # https://github.com/apache/pinot/blob/master/kubernetes/helm/pinot/values.yaml
    controller:
      external:
        enabled: false
    broker:
      external:
        enabled: false