apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cassandra
  namespace: cassandra
spec:
  interval: 5m
  targetNamespace: cassandra
  chart:
    spec:
      chart: cassandra
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
  # https://artifacthub.io/packages/helm/bitnami/cassandra
  # https://github.com/bitnami/charts/blob/main/bitnami/cassandra/values.yaml
    dbuser:
      user: andreyolv
      password: andreyolv
      # Login, enter inside container> cqlsh -u andreyolv -p andreyolv