apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cassandra
  namespace: cassandra
spec:
  interval: 5m
  targetNamespace: cassandra
  chart:
    spec:
      chart: k8ssandra-operator
      version: "v1.5.2"
      sourceRef:
        kind: HelmRepository
        name: cassandra
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
  # https://github.com/k8ssandra/k8ssandra-operator/blob/main/charts/k8ssandra-operator/values.yaml
    fullnameOverride: "cassandra-operator"
    global:
      clusterScoped: true