apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 2m
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      interval: 5m
  install:
    remediation:
      retries: 10
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Retain
      migratable: true
      defaultClassReplicaCount: 1

    defaultSettings:
      defaultReplicaCount: 1