apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 2m
  releaseName: longhorn
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 10
  values:
  # https://artifacthub.io/packages/helm/longhorn/longhorn
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
    enablePSP: true
    