apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kedacore.github.io/charts
      chart: keda
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  interval: 10m0s
  releaseName: keda
  targetNamespace: keda
  values:
    # TODO: Keda: support for additional labels
    # labels: kind/feature, priority/low, lifecycle/frozen, area/kubernetes
    # https://github.com/kedacore/charts/pull/179

    # additionalLabels:
    #   portefaix.xyz/version: v0.46.0

    logging:
      operator:
        level: info
        format: json
    prometheus:
      metricServer:
        enabled: true
        podMonitor:
          enabled: true
          additionalLabels:
            monitoring: portefaix
      operator:
        enabled: true
        podMonitor:
          enabled: true
          additionalLabels:
            monitoring: portefaix