apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kedacore.github.io/charts
      chart: keda
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  interval: 10m0s
  releaseName: keda
  targetNamespace: keda
  