apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.8.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    # CreateNamespace tells the Helm install action to create the HelmReleaseSpec.TargetNamespace if it does not exist yet.
    # CAUTION: Can be a limitation if you require specific namespace labels or annotations to exist; EG. PodSecurity
    createNamespace: true
    disableWait: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true