apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      version: "2.7.2"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 1m