apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 1m
  install:
    timeout: 10m
    remediation:
      retries: 3
  values:
  # https://artifacthub.io/packages/helm/rancher-stable/rancher
  # https://github.com/rancher/rancher/blob/release/v2.7/chart/values.yaml
    ingress:
      enabled: false