apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  interval: 1m
  chart:
    spec:
      chart: .
      version: "2.7.2"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 1m
    install:
    timeout: 10m
    remediation:
      retries: 3
  values:
  # https://github.com/rancher/rancher/blob/release/v2.7/chart/values.yaml