apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  releaseName: airbyte
  chart:
    spec:
      chart: airbyte
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: airbyte
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3