apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  releaseName: airbyte
  chart:
    spec:
      chart: airbyte
      version: 0.44.1
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: flux-system
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
  values:
  # https://artifacthub.io/packages/helm/airbyte/airbyte
