apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./web-app/flagger
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system