apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: '1.7.0'
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  install:
    timeout: 15m
    remediation:
      retries: 3
  values:
  # https://artifacthub.io/packages/helm/apache-airflow/airflow
  # https://github.com/apache/airflow/blob/main/chart/values.yaml
    #dags:
    #  persistence:
    #    enabled: true
    #    existingClaim: airflow-fileshare-dags
    #logs:
    #  persistence:
    #    enabled: true
    #    existingClaim: airflow-fileshare-logs