apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki-stack
spec:
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  targetNamespace: loki-stack
  values:
  # https://artifacthub.io/packages/helm/grafana/loki-stack
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
    fluent-bit:
      enabled: true
    grafana:
      enabled: true
    # login: admin
    # password: kubectl get secret --namespace loki-stack loki-stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo