apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trino
  namespace: virtualization
spec:
  releaseName: trino
  chart:
    spec:
      chart: trino
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: virtualization
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3