apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  releaseName: loki
  targetNamespace: loki
  values:
  # https://artifacthub.io/packages/helm/grafana/loki
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml