apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: armo
  namespace: kubescape
spec:
  releaseName: armo
  chart:
    spec:
      chart: armo
      sourceRef:
        kind: HelmRepository
        name: armo
        namespace: flux-system
  interval: 1h0m0s