apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubescape
  namespace: kubescape
spec:
  releaseName: kubescape
  chart:
    spec:
      chart: armo-cluster-components
      sourceRef:
        kind: HelmRepository
        name: armo
        namespace: flux-system
  interval: 1h0m0s
# chart deprecated  https://github.com/armosec/armo-helm