apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  targetNamespace: cilium
  storageNamespace: cilium
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  values:
  # https://artifacthub.io/packages/helm/cilium/cilium/1.9.0-rc3
  # https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml
    ipam:
      mode: kubernetes
    operator:
      replicas: 1
    certgen:
      hubble:
        ui:
          enabled: true