apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  targetNamespace: cilium
  storageNamespace: cilium
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  values:
    ipam:
      mode: kubernetes
    operator:
      replicas: 1