apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton
spec:
  releaseName: tekton
  targetNamespace: tekton
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: tekton-operator
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: true