apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-operator
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: flux-system
      version: 0.0.3
  interval: 60m0s
  values:
  # https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml