apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: prometheus-community
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: prometheus
      version: '18.4.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
    server:
      persistentVolume:
        enabled: false
    #extraScrapeConfigs: |
    #  - job_name: opencost
    #    honor_labels: true
    #    scrape_interval: 1m
    #    scrape_timeout: 10s
    #    metrics_path: /metrics
    #    scheme: http
    #    static_configs:
    #    - targets:
    #      - opencost.opencost:9003