apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: prometheus-community
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: prometheus
      version: '18.4.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system