apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.crossplane.io/stable
      chart: crossplane
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  interval: 5m
  releaseName: crossplane
  targetNamespace: crossplane
  test:
    enable: false # Enable helm test
  install:
    crds: CreateReplace
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 10m
  values:
    # customLabels:
    #   portefaix.xyz/version: v0.46.0
    metrics:
      enable: true