apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/kafka-ui
      sourceRef:
        kind: GitRepository
        name: provectus
        namespace: flux-system
  releaseName: kafka-ui
  values:
  # https://github.com/provectus/kafka-ui/blob/master/charts/kafka-ui/values.yaml
    service:
      type: ClusterIP
      port: 8080   
    env: 
    - name: KAFKA_CLUSTERS_0_NAME
      value: kafka-dev
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: http://kafka-dev-kafka-bootstrap.kafka.svc.cluster.local:9092
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
      value: http://schema-registry-cp-schema-registry.kafka.svc.cluster.local:8081
    - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
      value: http://ksqldb-server.kafka.svc.cluster.local:8088
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
      value: connect-cluster
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
      value: http://connect-cluster-connect-api.kafka.svc.cluster.local:8083
    yamlApplicationConfig:
      kafka:
        clusters:
          - name: kafka-dev
            bootstrapServers: kafka-dev-kafka-bootstrap.kafka.svc.cluster.local:9092
      auth:
        type: OAUTH2
        oauth2:
          client:
            github:
              provider: github
              clientId: xxx
              clientSecret: yyy
              scope:
                - read:org
              user-name-attribute: login
              custom-params:
                type: github       
      rbac:
        roles:
          - name: "admin"
            clusters:
              - kafka-dev
            subjects:
              - provider: oauth_github
                type: user
                value: "andreyolv"
            permissions:
              - resource: clusterconfig
                actions: all
              - resource: topic
                value: ".*"
                actions: [ "view","create","edit","delete","messages_produce" ]
              - resource: consumer
                value: ".*"
                actions: all
              - resource: schema
                value: ".*"
                actions: all
              - resource: connect
                value: ".*"
                actions: all
              - resource: ksql
                actions: all
#          - name: "readonly"
#            clusters:
#              - kafka-dev
#            subjects:
#              - provider: oauth_github
#                type: organization
#                value: "memelords_team"
#              - provider: oauth_github
#                type: user
#                value: "andreyolv"
#            permissions:
#              - resource: clusterconfig
#                actions: [ view ]
#              - resource: topic
#                value: "dev.*"
#                actions: [ view, create ]
#              - resource: consumer
#                value: ".*"
#                actions: [ view ]
#              - resource: schema
#                value: ".*"
#                actions: [ view ]
#              - resource: connect
#                value: ".*"
#                actions: [ view ]
#                actions: all
#              - resource: ksql
#                actions: [ view ]