apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./observability/elastic
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system