apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/observability/jaeger
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system