apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/observability/prometheus-community
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system