apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./observability/promtail
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system