apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: '6.47.1'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
  # https://artifacthub.io/packages/helm/grafana/grafana
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    adminUser: andreyolv
    adminPassword: andreyolv
    #admin:
    #  existingSecret: grafana-admin-secret
    #dashboardProviders:
    #  dashboardproviders.yaml:
    #    apiVersion: 1
    #    providers:
    #    - name: 'default'
    #      orgId: 1
    #      folder: ''
    #      type: file
    #      disableDeletion: false
    #      editable: true
    #      options:
    #        path: /var/lib/grafana/dashboards/default
    #dashboards:
    #  default:
    #    strimzi-kafka:
    #      file: 
