apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: komodor
  namespace: komodor
spec:
  releaseName: komodor
  chart:
    spec:
      chart: k8s-watcher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: komodorio
        namespace: flux-system
  targetNamespace: komodor
  install:
    createNamespace: true
  interval: 6h0m0s
  values:
  # https://github.com/komodorio/helm-charts/blob/master/charts/k8s-watcher/values.yaml