apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: robusta
  namespace: flux-system
spec:
  releaseName: robusta
  chart:
    spec:
      chart: robusta
      sourceRef:
        kind: HelmRepository
        name: robusta
        namespace: flux-system
  interval: 1h0m0s