apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: robusta
  namespace: flux-system
spec:
  interval: 15m
  url: https://robusta-charts.storage.googleapis.com
  timeout: 3m