apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: ">=0.6"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      interval: 1m
  targetNamespace: opentelemetry
  values:
  # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts