apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: weaveworks
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weaveworks-charts
        namespace: weaveworks
      interval: 5m
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    #    image:
    #      repository: ghcr.io/weaveworks/wego-app
    #      pullPolicy: IfNotPresent
    #      tag: "v0.9.0-rc.1"
    #image:
    # repository: ghcr.io/weaveworks/wego-app
    # tag: v0.12.0
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      username: admin
      # Change password by generating a new hash on https://bcrypt.online
      # bcrypt hash for password "flux"
      passwordHash: "$2y$10$iayIao/7JBdwGbyClt022uXQS2EvF5tkATd817z80Wdrs1zPw4dSC"