---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weaveworks-charts
  namespace: weaveworks
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/weaveworks/charts
  type: oci
  timeout: 3m