apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.28.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero
  interval: 5m
  releaseName: velero
  targetNamespace: velero
  values:

    serviceAccount:
      server:
        create: true
        name: velero
    metrics:
      enabled: true
