apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: 2.28.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  interval: 5m
  releaseName: velero
  targetNamespace: velero
  values:
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
    #configuration:
      #backupStorageLocation:
