apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./security/falco
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system