apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-bench
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/security/kube-bench
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system