# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: trivy
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./security/trivy
#   prune: false
#   sourceRef:
#     kind: GitRepository
#     name: flux-system