apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: schema-registry
  namespace: kafka
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/cp-schema-registry
      sourceRef:
        kind: GitRepository
        name: confluent
        namespace: flux-system
  releaseName: schema-registry
  values:
  # https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-schema-registry/values.yaml
    kafka:
      enabled: false
      bootstrapServers: kafka-dev-kafka-bootstrap:9092
      fullnameOverride: sr