apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30s
  chart:
    spec:
      chart: harbor
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
  values:
  # https://artifacthub.io/packages/helm/harbor/harbor
  # https://github.com/goharbor/harbor-helm/blob/master/values.yaml
    expose:
      type: clusterIP
    persistence:
      enabled: false
    existingSecretAdminPasswordKey: andreyolv
    harborAdminPassword: andreyolv