apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-ui
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/ide-ui/flux-ui
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system