apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq
spec:
  interval: 5m
  releaseName: rabbitmq-cluster-operator
  install:
    timeout: 10m
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 3.x
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      timeout: 10m
  values:
  # https://artifacthub.io/packages/helm/bitnami/rabbitmq-cluster-operator
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml