apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq
spec:
  interval: 1h
  releaseName: rabbitmq-cluster-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 3.x
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml